Implement basic ext4 filesystem
frozenpeach-dev/bootloader pull request #2
Opened 2023-07-19 16:32 UTC by raphfaur

2023-07-20 22:51 UTC, sleiderr requested changes

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/util/debug.rs
> +        printc(10);
Tu peux je pense utiliser `printc(b'\n')` plutôt que de devoir utiliser la valeur correspondante, c'est sûrement plus clair à la lecture.

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +        }
```suggestion
        partition.read(n * block_size_bytes, block_size_bytes, buffer)
```

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +        printc(13);
Ca pourrait valoir le coup de créer une fonction ou macro de type `println` vu que ce pattern est très souvent répété.

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +        match partition.read(inode_address,512, 0x1500 ) {
```suggestion
        match partition.read(inode_address, 512, 0x1500) {
```

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +        return inode;
```suggestion
        inode
```

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +    pub i_mode : u16,
à titre informatif, c'est quoi ton critère pour mettre un champ en public ou pas ? et pour choisir quand utiliser un getter plutôt que de rendre le champ complètement non protégé ?

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +        return self.explore_next_layer(mem_offset , n , block_size, partition);
```suggestion
        self.explore_next_layer(mem_offset , n, block_size, partition)
```
si tu préfères laisser les return, tu peux

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +                    let a = (extent.ee_start_lo as u64 + ((extent.ee_start_hi as u64) << 32)) + (n - extent.ee_block) as u64;
allocation pas nécessaire

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +                let _ = partition.read(next_block_address as u32, block_size, mem_offset + block_size);
Si ça peut échouer, passe le type de retour en `Result<u64, ()>` en suivant la suggestion: 
```suggestion
                partition.read(next_block_address as u32, block_size, mem_offset + block_size)?;
```

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +        return  0
```suggestion
        0
```

2023-07-20 22:51 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +
```suggestion
```

2023-07-22 18:01 UTC, raphfaur commented on src/bios/flib/src/util/debug.rs
> +        printc(10);
```suggestion
        printc(b'\n');
```

2023-07-22 18:07 UTC, raphfaur commented on src/bios/flib/src/fs/ext4.rs
> +        printc(13);
POur remplacer quelle partie exactement ?

2023-07-22 18:07 UTC, raphfaur commented on src/bios/flib/src/fs/ext4.rs
> +    pub i_mode : u16,
J'ay a pas réfléchi ct surtout au début quand tout lagait il y avait des trucs sus donc je mettais des trucs en public pour pouvoir debug plus facilement depuis main
Mais t'as raison faudrait clean ça

2023-07-22 18:07 UTC, raphfaur commented on src/bios/flib/src/fs/ext4.rs
> +                    let a = (extent.ee_start_lo as u64 + ((extent.ee_start_hi as u64) << 32)) + (n - extent.ee_block) as u64;
Y a eu un debug un moment mdr

2023-07-22 18:07 UTC, raphfaur commented on src/bios/flib/src/fs/ext4.rs
> +                    return a
```suggestion
                    return (extent.ee_start_lo as u64 + ((extent.ee_start_hi as u64) << 32)) + (n - extent.ee_block) as u64
```

2023-07-22 18:07 UTC, raphfaur commented on src/bios/flib/src/fs/ext4.rs
> +                    let a = (extent.ee_start_lo as u64 + ((extent.ee_start_hi as u64) << 32)) + (n - extent.ee_block) as u64;
```suggestion
```

2023-07-22 18:07 UTC, raphfaur commented on src/bios/flib/src/fs/ext4.rs
> +                let _ = partition.read(next_block_address as u32, block_size, mem_offset + block_size);
Je fais pas te cacher que j'ai pas trop travaillé le fait de handle les erreurs et tout, faudrait probablement que je le fasse

2023-07-22 21:07 UTC, sleiderr commented on src/bios/flib/src/fs/ext4.rs
> +        printc(13);
Lignes 130 et 131 (le retour à la ligne)

2023-08-18 21:46 UTC, sleiderr commented
We should work on implementing that as it sounds like the next step needed in order to boot anything @raphfaur

2023-08-18 22:00 UTC, raphfaur commented
> We should work on implementing that as it sounds like the next step needed in order to boot anything @raphfaur 

Yes i think so.
It was working fine, i think we just need to rewrite a bit of code to use the buddy allocator instead of writing stuff at raw addresses (because that's what i did when there was no higher level tools in the bootloader)

2023-12-30 00:02 UTC, sleiderr approved these changes

2023-12-30 00:48 UTC, merged