feat: Implement Interrupt Descriptor Table and Interrupt Routines
frozenpeach-dev/bootloader pull request #20
Opened 2023-08-05 01:00 UTC by raphfaur

2023-08-07 20:59 UTC, sleiderr requested changes

2023-08-07 20:59 UTC, sleiderr commented on src/bios/f-init32/Cargo.toml
> +f-macros = {path = "../f-macros/"}
```suggestion
flib = { path = "../flib/", features = ["alloc"] }
f-macros = { path = "../f-macros/" }
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/f-init32/Cargo.toml
> +numtoa = "0.2.4"
```suggestion
numtoa = "0.2"
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/f-init32/src/interrupts/handlers.rs
> +
faut retirer ça non ?
```suggestion
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/f-macros/Cargo.toml
> +proc-macro2 = "1.0.66"
```suggestion
proc-macro2 = "1.0"
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/f-macros/Cargo.toml
> +quote = "1.0.32"
```suggestion
quote = "1.0"
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/f-macros/Cargo.toml
> +syn = { version = "2.0.28", features = ["full"]}
```suggestion
syn = { version = "2.0.28", features = ["full"] }
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/f-macros/src/lib.rs
> +/// specific cases
```suggestion
/// specific cases.
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    /// Writes the [Table] to a given offset. You have to ensure that there is enough
```suggestion
    /// Writes the `Table` to a given offset. You have to ensure that there is enough
```
Je suis d'avis d'éviter les liens vers elle-même quand on commente des élements de la struct

2023-08-07 20:59 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    pub fn get_entry_mut(&mut self, index : usize) -> Option<&mut GateDescriptor>{
```suggestion
    pub fn get_entry_mut(&mut self, index : usize) -> Option<&mut GateDescriptor> {
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    pub fn get_entry(&self, index : usize) -> Option<&GateDescriptor>{
```suggestion
    pub fn get_entry(&self, index : usize) -> Option<&GateDescriptor> {
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    /// Populates the [Table] with default [`GateDescriptor`] to reach 256 entries (required)
```suggestion
    /// Populates the `Table` with default [`GateDescriptor`] to reach 256 entries (required)
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    /// Populates the [Table] with given [`GateDescriptor`] to reach 256 entries (required)
```suggestion
    /// Populates the `Table` with given [`GateDescriptor`] to reach 256 entries (required)
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +
```suggestion
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    /// Returns the [SegmentSelector] configured to use loaded GDT
```suggestion
    /// Returns the `SegmentSelector` configured to use loaded GDT.
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    /// Returns the [SegmentSelector] configured with the given privileges
```suggestion
    /// Returns the `SegmentSelector` configured with the given privileges.
```

2023-08-07 20:59 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    }
pourquoi tu fais fn(mut self) -> Self et pas fn(&mut self) -> () ?

2023-08-07 21:07 UTC, sleiderr commented on src/bios/f-init32/src/interrupts/handlers.rs
> +/// ```
```suggestion
///
/// # Examples:
///
/// ```
/// #[interrupt]
/// pub fn _int0x00() {
///     do_something()
/// }
/// ```
///
```

2023-08-07 21:07 UTC, sleiderr commented on src/bios/f-init32/src/interrupts/handlers.rs
> +/// The naming convention implies that interrupt are named as follows :
```suggestion
/// The naming convention implies that interrupt are named as follows :
///
```

2023-08-07 21:07 UTC, sleiderr commented on src/bios/f-init32/src/interrupts/handlers.rs
> +///```
```suggestion
/// This one will provide a generic variable :
/// ```
/// let int_code : usize
/// ```
///
/// usable in your default template to perform generic handle actions at runtime.
///
/// ```
/// #[interrupt_default]
/// pub fn _int_default(){
///      print!("{}", int_code);
/// }
/// ```
///
```

2023-08-07 21:07 UTC, sleiderr commented on src/bios/f-init32/src/interrupts/handlers.rs
> +/// ```
```suggestion
/// e.g. This example shows how you would save the idt at offset 0x8
///
/// ```
/// #[interrupt_descriptor_table(0x8)]
/// mod interrupts;
/// ```
///
/// Loading of the table will then be achieved by calling the following function
/// from your main function.
///
/// ```
/// generate_idt()
/// ```
```

2023-08-07 21:07 UTC, sleiderr commented on src/bios/f-init32/src/interrupts/handlers.rs
> +use flib::debug::debug::print_str;
```suggestion
```

2023-08-07 21:07 UTC, sleiderr commented on src/bios/f-init32/src/interrupts/handlers.rs
> +    print_str(format!("{}", int_code).as_str(), 0);
```suggestion
    println!("{}", int_code);
```

2023-08-07 21:07 UTC, sleiderr commented on src/bios/f-init32/src/interrupts/handlers.rs
> +use flib::{print, scheduler_ref};
```suggestion
use flib::{println, scheduler_ref};
```

2023-08-07 21:07 UTC, sleiderr commented on src/bios/f-macros/src/lib.rs
> +/// ```
```suggestion
/// This function will then have to be called from the main function.
///
/// ```
/// generate_idt();
/// ```
```

2023-08-07 21:08 UTC, sleiderr commented on src/bios/flib/src/lib.rs
> +
```suggestion
```

2023-08-07 21:11 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +use numtoa::NumToA;
Do you still use `numtoa`? didn't see it used anywhere, and we shouldn't need that anymore (at least in protected mode) with the formatting macros.

2023-08-07 21:17 UTC, raphfaur commented on src/bios/flib/src/idt/idt.rs
> +use numtoa::NumToA;
You're right, I was using it to debug on protected mode before vesa got merged
```suggestion
```

2023-08-07 21:17 UTC, raphfaur commented on src/bios/flib/src/idt/idt.rs
> +    }
It is useful for chaining when creating SegmentSelectors

2023-08-07 21:21 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    }
php style 😁

2023-08-07 21:22 UTC, sleiderr commented on src/bios/f-init32/Cargo.toml
> +numtoa = "0.2"
```suggestion
```

2023-08-07 21:24 UTC, raphfaur commented on src/bios/flib/src/idt/idt.rs
> +    }
overleve style

2023-08-09 14:50 UTC, sleiderr commented on src/bios/flib/src/io/utils.rs
c'était déjà implémenté

2023-08-09 22:00 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +/// Loads [IDTDescriptor] in the CPU IDTR using `lidt` instruction
```suggestion
/// Loads [`IDTDescriptor`] in the CPU IDTR using `lidt` instruction
```

2023-08-09 22:00 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    /// Stores the [IDTDescriptor] to a given location in memory
```suggestion
    /// Stores the [`IDTDescriptor`] to a given location in memory
```

2023-08-09 22:00 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +    /// Set p bit to 1. One must always call [set_valid()] on a [GateDescriptor]
```suggestion
    /// Set p bit to 1. One must always call `set_valid()` on a [`GateDescriptor`]
```

2023-08-09 22:01 UTC, sleiderr commented on src/bios/flib/src/idt/idt.rs
> +/// The [SegmentSelector] describes the segment where the Routine is stored.
```suggestion
/// The `SegmentSelector` describes the segment where the Routine is stored.
```

2023-08-09 22:08 UTC, sleiderr approved these changes

2023-08-09 22:08 UTC, merged