Implements `APIC` and `ioAPIC`s support
frozenpeach-dev/bootloader pull request #43
Opened 2023-08-14 13:23 UTC by raphfaur

2023-08-17 17:06 UTC, sleiderr requested changes

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +        let high = msr >> 32 as u32;
```suggestion
        let high = (msr >> 32) as u32;
```
It casts 32 to a u32 instead of the result of the shift.

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +        }
```suggestion
        for (i, ioapic) in entries.t1.into_iter().enumerate() {
            let a = u32::from_le_bytes(ioapic.io_apic_address);
            let mut io = IoAPIC::new(a as usize);
            io.setup(i);
            ioapics.push(io);
        }
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    }
These functions are not necessary, they are already implemented in `fzboot::x86::msr` as `msr_read` and `msr_write` (which I marked as an `unsafe fn` as it makes sense for this type of function).
There are no major differences between the implementations, so that should be changed to use `msr_read` and `msr_write` instead.

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +        println!("msr : {:#064b}", msr);
```suggestion

```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    }
That might be sending too many lines to read for the the user, maybe most of these could be condensed on one single line (`Local APIC  physical_id =    size =...`) instead.

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +            register_base: 0xfee00000,
I suppose that is the hardcoded value that shouldn't be ?
I will take a look at the ACPI implementation to allow easier retrieval of the memory address of the table.

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +//! APIC is a more recent interrupt controller for intel processors.
```suggestion
//! APIC is a more recent interrupt controller for Intel processors.
```
which ones ? what does it add / what are the main use cases of this for the bootloader ?

2023-08-17 17:06 UTC, sleiderr commented on src/io/acpi/madt.rs
> +    pub gsib: [u8; 4],
Using arrays should not be necessary anymore ?

2023-08-17 17:06 UTC, sleiderr commented on src/io/acpi/madt.rs
> +                    entries.t1.push(entry.clone());
I'm not sure the clone is necessary ?

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +        for _i in 0..50 {
```suggestion
        for _ in 0..50 {
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +/// ```
```suggestion
/// To learn more about how to configure each kind of entry, refer to Intel documentation.
///
/// # Examples
///
/// ```
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// # Errors
```suggestion
    /// # Errors
    ///
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// # Errors
```suggestion
    /// # Errors
    ///
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// # Errors
```suggestion
    /// # Errors
    ///
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// # Errors
```suggestion
    /// # Errors
    ///
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// # Errors
```suggestion
    /// # Errors
    ///
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// # Examples
```suggestion
    /// # Examples
    ///
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// # Errors
```suggestion
    /// # Errors
    ///
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// # Errors
```suggestion
    /// # Errors
    ///
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// To prevent undefined behaviour, this function may result as an [`Err`]
```suggestion
    /// Joins the given cluster.
    ///
    /// # Errors
    ///
    /// To prevent undefined behaviour, this function may result as an [`Err`]
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// # Errors
```suggestion
    /// # Errors
    ///
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// There is no reason for this function to fail but we need to ensure
```suggestion
    /// such as [`Self::join_cluster`]
    ///
    /// # Errors
    ///
    /// There is no reason for this function to fail but we need to ensure
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// There is no reason for this function to fail but we need to ensure
```suggestion
    /// such as [`Self::join`] or [`Self::leave`]
    ///
    /// # Errors
    ///
    /// There is no reason for this function to fail but we need to ensure
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// A common example is to overwrite second entry (ie offset 1) in order to handle
```suggestion
    /// # Examples
    ///
    /// A common example is to overwrite second entry (ie offset 1) in order to handle
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// As an example, this is how you would send an IPI to self using [`DestinationFormat::CLUSTER`]
```suggestion
    /// # Examples
    ///
    /// As an example, this is how you would send an IPI to self using [`DestinationFormat::CLUSTER`]
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// This mode is usually used to let the legacy 8259 PIC use the LINT0 pin.
```suggestion
    /// # Examples
    ///
    /// This mode is usually used to let the legacy 8259 PIC use the LINT0 pin.
```

2023-08-17 17:06 UTC, sleiderr commented on src/io/acpi/madt.rs
Maybe it would be nice to add a little bit more documentation for this file.

2023-08-17 17:06 UTC, sleiderr commented on src/io/apic/mod.rs
> +    /// ```plaintext
```suggestion
    /// Returns the APIC MSR.
    ///
    /// It has the following structure :
    ///
    /// ```plaintext
```

2023-08-18 22:58 UTC, raphfaur commented on src/io/apic/mod.rs
> +    }
Yes I was planning to  use `fzboot::x86::msr` but the PR was not merged when i needed these functions.

2023-08-18 22:59 UTC, raphfaur commented on src/io/apic/mod.rs
> +    }
yep

2023-08-18 23:14 UTC, raphfaur reviewed
I'm gonna change a few things, especially regarding #46 and MSR utils

2023-08-18 23:14 UTC, raphfaur commented on src/io/acpi/madt.rs
> +                    entries.t1.push(entry.clone());
neither am i , gonna look

2023-08-18 23:14 UTC, raphfaur commented on src/io/acpi/madt.rs
Yeah i think so, I was just mentally dead after spending one day commenting and reviewing APIC file 😁

2023-08-18 23:14 UTC, raphfaur commented on src/io/acpi/madt.rs
> +    pub gsib: [u8; 4],
Yeah didn't remember to revert it.

2023-08-18 23:14 UTC, raphfaur commented on src/io/apic/mod.rs
> +//! APIC is a more recent interrupt controller for intel processors.
Ok, gonna write a bit more about it in the doc

2023-08-18 23:14 UTC, raphfaur commented on src/io/apic/mod.rs
> +            register_base: 0xfee00000,
That's not this one.
`0xfee00000` is the default address for APIC registers, that's why the value is hardcoded there.
Nobody should really use it. Do you think I should take it off ?

2024-01-03 15:23 UTC, sleiderr approved these changes

2024-01-03 15:31 UTC, merged